import = ["/home/fergus/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[shell]
args = ["-l", "-c", "tmux attach 2>/dev/null || tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1

[window.dimensions]
columns = 120
lines = 50

[window.padding]
x = 6
y = 6
