# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$cmd_duration\
$character
"""

add_newline = false

[line_break]
disabled = true

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

